# Recetas de platos chilenos: gramos de ingrediente por 100 g de plato terminado.
# Las proporciones son estimaciones de preparación casera estándar y quedan
# guardadas en la base para que Camilo pueda auditarlas y corregirlas.
# "sal" se expresa en gramos e incluye la sal de cocción habitual.

RECETAS = {
 "marraqueta": ("Marraqueta / pan batido", "Cereal",
    ["marraqueta","pan batido","pan frances"],
    {"harina": 62, "sal": 1.2}),
 "hallulla": ("Hallulla", "Cereal", ["hallulla"],
    {"harina": 58, "manteca": 8, "sal": 1.1, "polvo_hornear": 1.5}),
 "sopaipilla": ("Sopaipilla", "Cereal", ["sopaipillas"],
    {"harina": 45, "zapallo": 20, "manteca": 14, "sal": 1.0}),
 "empanada_pino": ("Empanada de pino", "Procesado", ["empanada","empanada de horno"],
    {"harina": 34, "vacuno": 20, "cebolla": 22, "huevo": 6, "manteca": 7, "sal": 1.2, "aji_color": 0.3}),
 "empanada_queso": ("Empanada de queso", "Procesado", ["empanada frita"],
    {"harina": 38, "queso_gauda": 26, "aceite": 12, "sal": 1.0}),
 "completo": ("Completo", "Procesado", ["hot dog","completo italiano"],
    {"pan_blanco": 35, "vienesa": 25, "palta": 18, "tomate": 15, "sal": 0.6}),
 "churrasco": ("Churrasco / sándwich de carne", "Procesado", ["sandwich de carne","barros luco"],
    {"pan_blanco": 40, "vacuno": 35, "queso_gauda": 10, "sal": 0.8}),
 "cazuela_vacuno": ("Cazuela de vacuno", "Plato preparado", ["cazuela"],
    {"vacuno": 14, "papa_cocida": 22, "zapallo_cocido": 14, "choclo_cocido": 8, "cebolla": 5, "arroz_crudo": 2, "sal": 0.7}),
 "cazuela_ave": ("Cazuela de ave", "Plato preparado", ["cazuela de pollo"],
    {"pollo": 14, "papa_cocida": 22, "zapallo_cocido": 14, "choclo_cocido": 8, "cebolla": 5, "arroz_crudo": 2, "sal": 0.7}),
 "charquican": ("Charquicán", "Plato preparado", ["charquican"],
    {"papa_cocida": 34, "zapallo_cocido": 22, "vacuno": 12, "choclo_cocido": 8, "cebolla": 6, "aceite": 3, "sal": 0.8}),
 "porotos_granados": ("Porotos granados", "Legumbre", ["porotos con mazamorra"],
    {"porotos_negros": 34, "zapallo_cocido": 22, "choclo_cocido": 16, "cebolla": 6, "aceite": 3, "sal": 0.8}),
 "pastel_choclo": ("Pastel de choclo", "Plato preparado", ["pastel de maiz"],
    {"choclo_cocido": 48, "vacuno": 16, "cebolla": 10, "leche": 8, "huevo": 5, "azucar": 3, "sal": 0.9}),
 "humita": ("Humita", "Plato preparado", ["humitas"],
    {"choclo_cocido": 68, "cebolla": 8, "leche": 6, "manteca": 5, "sal": 0.9}),
 "carbonada": ("Carbonada", "Plato preparado", ["carbonada"],
    {"vacuno": 12, "papa_cocida": 20, "zapallo_cocido": 12, "zanahoria_cocida": 8, "choclo_cocido": 7, "fideo_crudo": 3, "cebolla": 5, "sal": 0.7}),
 "lentejas_guisadas": ("Lentejas guisadas", "Legumbre", ["lentejas"],
    {"lenteja_cocida": 62, "cebolla": 8, "zanahoria": 6, "aceite": 3, "sal": 0.8}),
 "arroz_pollo": ("Arroz con pollo", "Plato preparado", ["arroz con pollo"],
    {"arroz_crudo": 26, "pollo": 18, "cebolla": 6, "zanahoria": 5, "aceite": 3, "sal": 0.8}),
 "tallarines_salsa": ("Tallarines con salsa de tomate", "Plato preparado", ["tallarines","pasta con salsa"],
    {"fideo_crudo": 30, "tomate": 30, "cebolla": 6, "aceite": 3, "sal": 0.8}),
 "pure_papas": ("Puré de papas", "Verdura", ["pure"],
    {"papa_cocida": 72, "leche": 14, "mantequilla": 5, "sal": 0.7}),
 "ensalada_chilena": ("Ensalada chilena", "Verdura", ["ensalada de tomate y cebolla"],
    {"tomate": 62, "cebolla": 28, "aceite": 5, "sal": 0.6}),
 "pebre": ("Pebre", "Condimento", ["pebre chileno"],
    {"tomate": 45, "cebolla": 30, "cilantro": 10, "aceite": 8, "sal": 1.2}),
 "papas_cocidas": ("Papas cocidas", "Verdura", ["papa cocida","papas hervidas"],
    {"papa_cocida": 98, "sal": 0.4}),
 "papas_duquesa": ("Papas doradas al horno", "Verdura", ["papas al horno"],
    {"papa": 85, "aceite": 8, "sal": 0.7}),
 "pollo_asado": ("Pollo asado", "Carne", ["pollo al horno"],
    {"pollo": 92, "aceite": 3, "sal": 1.0}),
 "costillar_cerdo": ("Costillar de cerdo", "Carne", ["costillar"],
    {"cerdo": 92, "aceite": 3, "sal": 1.1}),
 "merluza_frita": ("Merluza frita", "Pescado", ["pescado frito","merluza"],
    {"merluza": 74, "harina": 8, "aceite": 12, "sal": 0.9}),
 "merluza_vapor": ("Merluza al vapor", "Pescado", ["pescado al vapor"],
    {"merluza": 97, "sal": 0.5}),
 "chorrillana": ("Chorrillana", "Plato preparado", ["chorrillana"],
    {"papa": 42, "vacuno": 22, "cebolla": 14, "huevo": 10, "aceite": 9, "sal": 1.0}),
 "arroz_leche": ("Arroz con leche", "Postre", ["arroz con leche"],
    {"arroz_crudo": 14, "leche": 62, "azucar": 10}),
 "leche_asada": ("Leche asada", "Postre", ["leche asada","flan"],
    {"leche": 66, "huevo": 18, "azucar": 14}),
 "mote_huesillo": ("Mote con huesillo", "Postre", ["mote con huesillo"],
    {"trigo_mote": 12, "durazno_conserva": 16, "azucar": 10}),
 "acelga_cocida": ("Acelga cocida", "Verdura", ["acelgas"],
    {"acelga_cocida_ing": 96, "aceite": 2, "sal": 0.5}),
 "longaniza": ("Longaniza", "Procesado", ["longaniza chilena"],
    {"cerdo": 78, "manteca": 12, "sal": 2.2, "aji_color": 0.5}),
 "queso_chanco": ("Queso chanco", "Lácteo", ["queso chanco","queso mantecoso"],
    {"queso_gauda": 100}),
 "palta_molida": ("Palta molida", "Fruta", ["palta molida","guacamole"],
    {"palta": 92, "sal": 0.6}),
 "te_con_leche": ("Té con leche", "Bebida", ["te con leche"],
    {"leche": 25, "azucar": 5}),
}
