# Mapeo explícito: id nuestro -> descripción exacta en USDA SR Legacy.
# Escrito a mano para evitar los falsos positivos del matcher automático.
MAPEO = {
    # Frutas
    "manzana": "Apples, raw, with skin (Includes foods for USDA's Food Distribution Program)",
    "platano": "Bananas, raw",
    "naranja": "Oranges, raw, all commercial varieties",
    "pera": "Pears, raw",
    "uva": "Grapes, red or green (European type, such as Thompson seedless), raw",
    "sandia": "Watermelon, raw",
    "melon": "Melons, cantaloupe, raw",
    "fresa": "Strawberries, raw",
    "kiwi": "Kiwifruit, green, raw",
    "pina": "Pineapple, raw, all varieties",
    "mango": "Mangos, raw",
    "durazno": "Peaches, yellow, raw",
    "ciruela": "Plums, raw",
    "cereza": "Cherries, sweet, raw",
    "limon": "Lemons, raw, without peel",
    "aguacate": "Avocados, raw, all commercial varieties",
    "papaya": "Papayas, raw",
    "mandarina": "Tangerines, (mandarin oranges), raw",
    "higo": "Figs, raw",
    "datil": "Dates, medjool",
    "arandano": "Blueberries, raw",
    "frambuesa": "Raspberries, raw",
    "granada": "Pomegranates, raw",
    "guayaba": "Guavas, common, raw",
    # Verduras
    "papa": "Potatoes, flesh and skin, raw",
    "tomate": "Tomatoes, red, ripe, raw, year round average",
    "lechuga": "Lettuce, butterhead (includes boston and bibb types), raw",
    "zanahoria": "Carrots, raw",
    "brocoli": "Broccoli, raw",
    "espinaca": "Spinach, raw",
    "coliflor": "Cauliflower, raw",
    "pepino": "Cucumber, with peel, raw",
    "calabacin": "Squash, summer, zucchini, includes skin, raw",
    "berenjena": "Eggplant, raw",
    "pimiento": "Peppers, sweet, red, raw",
    "cebolla": "Onions, raw",
    "ajo": "Garlic, raw",
    "apio": "Celery, raw",
    "champinon": "Mushrooms, white, raw",
    "calabaza": "Pumpkin, raw",
    "remolacha": "Beets, raw",
    "esparrago": "Asparagus, raw",
    "col": "Cabbage, raw",
    "acelga": "Chard, swiss, raw",
    "aceituna": "Olives, ripe, canned (small-extra large)",
    # Legumbres
    "frijol_negro": "Beans, black, mature seeds, cooked, boiled, without salt",
    "lenteja": "Lentils, mature seeds, cooked, boiled, without salt",
    "garbanzo": "Chickpeas (garbanzo beans, bengal gram), mature seeds, cooked, boiled, without salt",
    "guisante": "Peas, green, cooked, boiled, drained, without salt",
    "haba": "Broadbeans (fava beans), mature seeds, cooked, boiled, without salt",
    # Cereales
    "arroz_blanco": "Rice, white, long-grain, regular, enriched, cooked",
    "arroz_integral": "Rice, brown, long-grain, cooked (Includes foods for USDA's Food Distribution Program)",
    "pasta": "Pasta, cooked, enriched, without added salt",
    "pan_blanco": "Bread, white, commercially prepared, low sodium, no salt",
    "pan_integral": "Bread, whole-wheat, commercially prepared",
    "avena": "Cereals, QUAKER, Quick Oats, Dry",
    "quinoa": "Quinoa, cooked",
    "maiz": "Corn, sweet, yellow, cooked, boiled, drained, without salt",
    "tortilla_maiz": "Tortillas, ready-to-bake or -fry, corn",
    "tortilla_harina": "Tortillas, ready-to-bake or -fry, flour, refrigerated",
    # Lácteos
    "leche_entera": "Milk, whole, 3.25% milkfat, without added vitamin A and vitamin D",
    "leche_descremada": "Milk, nonfat, fluid, with added vitamin A and vitamin D (fat free or skim)",
    "yogur": "Yogurt, plain, whole milk",
    "queso_fresco": "Cheese, fresh, queso fresco",
    "queso_cheddar": "Cheese, cheddar (Includes foods for USDA's Food Distribution Program)",
    "queso_crema": "Cheese, cream",
    "mantequilla": "Butter, salted",
    # Carnes y pescados
    "pollo": "Chicken, broilers or fryers, breast, meat only, cooked, roasted",
    "res": "Beef, ground, 85% lean meat / 15% fat, patty, cooked, broiled",
    "cerdo": "Pork, fresh, loin, center loin (chops), bone-in, separable lean only, cooked, broiled",
    "salmon": "Fish, salmon, Atlantic, farmed, cooked, dry heat",
    "atun": "Fish, tuna, light, canned in water, drained solids (Includes foods for USDA's Food Distribution Program)",
    "huevo": "Egg, whole, raw, fresh",
    "camaron": "Crustaceans, shrimp, cooked",
    "pavo": "Turkey, breast, from whole bird, meat only, with added solution, roasted",
    "tofu": "Tofu, raw, firm, prepared with calcium sulfate",
    # Frutos secos
    "almendra": "Nuts, almonds",
    "nuez": "Nuts, walnuts, english",
    "mani": "Peanuts, all types, raw",
    "girasol": "Seeds, sunflower seed kernels, dried",
    "chia": "Seeds, chia seeds, dried",
    # Procesados
    "pan_hamburguesa": "Rolls, hamburger or hotdog, plain",
    "papas_fritas": "Snacks, potato chips, plain, salted",
    "jamon": "Ham, sliced, regular (approximately 11% fat)",
    "tocino": "Pork, cured, bacon, cooked, baked",
    "salchicha": "Frankfurter, beef, unheated",
    "queso_procesado": "Cheese, pasteurized process, American, fortified with vitamin D",
    "chocolate": "Chocolate, dark, 70-85% cacao solids",
    "galleta": "Cookies, sugar, commercially prepared, regular (includes vanilla)",
    "pizza": "Pizza, cheese topping, regular crust, frozen, cooked",
    # Condimentos
    "salsa_soya": "Soy sauce made from soy (tamari)",
    "sal": "Salt, table",
    "caldo_cubo": "Soup, beef broth, cubed, dry",
    "ketchup": "Catsup",
    "mostaza": "Mustard, prepared, yellow",
    "mayonesa": "Salad dressing, mayonnaise, regular",
    # Bebidas
    "cola": "Beverages, carbonated, cola, regular",
    "jugo_naranja": "Orange juice, chilled, includes from concentrate",
    "cafe": "Beverages, coffee, brewed, prepared with tap water",
    "te": "Beverages, tea, black, brewed, prepared with tap water",
    "agua_coco": "Nuts, coconut water (liquid from coconuts)",
    "cerveza": "Alcoholic beverage, beer, regular, all",
    "vino": "Alcoholic beverage, wine, table, red",
    "leche_almendra": "Beverages, almond milk, unsweetened, shelf stable",
    "jugo_tomate": "Tomato juice, canned, with salt added",
}
